#*******************************************************************************
#
# Project: Modelling eGFR slope
# Date:    01-Dec-2023
# Authors: Robert Fletcher and Niels Jongs
# Purpose: Model eGFR slope using synthetic data
# Contact: rfletcher@georgeinstitute.org.au | n.jongs@umcg.nl
#
#*******************************************************************************


# Notes -------------------------------------------------------------------

# This is a reproducible example of the code used to calculate estimated 
# glomerular filtration rate (eGFR) slope. It should allow you to set-up your
# data in the correct format and to replicate the analyses in your respective
# trial

# Please see the repository README.md for further information or see our contact
# details above


# Install dependencies (if not currently installed) -----------------------

# Library names
libs <- c("glue", "multcomp", "lme4", "tidyverse")

# Install libraries
install.packages(setdiff(libs, rownames(installed.packages())))


# Load libraries ----------------------------------------------------------

library(glue)
library(nlme)
library(multcomp)
library(tidyverse)


# Define variables --------------------------------------------------------

# Path to cloned repository
path <- 
  stringr::str_remove(
    dirname(rstudioapi::getSourceEditorContext()$path), "/code$"
  )

# Set knot point for spline. This is 3 weeks/21 days in the CREDENCE trial, i.e.
# the first study visit, as is the point at which the initial acute drop with
# SGLT2 inhibition is observed. You'll want to specify this according to the 
# data available in your trial. For instance, in DAPA-CKD, the first study visit
# post-randomisation is at two weeks, so `k` would be set to 14
k <- 21


# Source functions --------------------------------------------------------

source(glue::glue("{path}/src/generate_synthetic_data.R"))
source(glue::glue("{path}/src/compute_slope.R"))


# Load data ---------------------------------------------------------------

bl <- generate_synthetic_data(.table = "baseline")
fu <- generate_synthetic_data(.table = "follow-up")

# If the function above refuses to run for you, the two datasets generated by 
# this function are also available in CSV format in the `data` sub-directory of
# this repository. Use the following functions to load those files:

# bl <- readr::read_csv("{path}/data/synthetic_trial_baseline.csv")
# fu <- readr::read_csv("{path}/data/synthetic_trial_egfr_follow_up.csv")


# Prepare data ------------------------------------------------------------

# Treatment arms (filtering for on-treatment individuals only)
arm <- bl |> 
  dplyr::filter(trtfl == "Y") |> 
  dplyr::select(usubjid, trt01pn, blglp1, strata) |> 
  dplyr::mutate(blglp1 = dplyr::if_else(blglp1 == "Y", 1, 0))

# Repeat eGFR (filtering for on-treatment values and those flagged for analysis)
gfr <- fu |> 
  dplyr::filter(dplyr::if_all(c(trtfl, anl01fl), \(x) x == "Y")) |> 
  dplyr::distinct(usubjid, aval, ady, base, avisitn)

# Join
gfr_c <- arm |> 
  dplyr::left_join(gfr, by = dplyr::join_by(usubjid), multiple = "all") |> 
  dplyr::mutate(
    # Convert days from baseline to years
    time = ady / 365.25,
    # Generate spline term
    spline = dplyr::if_else(time >= k / 365.25, time - k / 365.25, 0)
  )

# This is probably the most important aspect of the code: formatting the data to
# the required specifications to fit the model. The synthetic data used in this 
# reprex should give you an idea of the format, but consult the repository 
# README if you're unsure about anything or would like a more detailed
# explanation


# Fit model (whole population) --------------------------------------------

# Fit mixed effects model with unstructured residual variance-covariance matrix
fit <- lme4::lmer(
  aval ~ base + strata + time * trt01pn + spline * trt01pn - 1 + 
  (time | usubjid), data = gfr_c
)

# The above model is for the overall trial population. Subgroup-specific 
# analyses are covered further down

# Please see the repository README if you'd like more information on 
# specification of the model parameters


# Extract model results (whole population) --------------------------------

# Define proportion of total slope accounted-for by chronic slope (1095.75 is
# the equivalent of 3 years in days, so we if we subtract the number of days in 
# the acute slope, approximately 21 days or 3 weeks, we get this proportion 
prop <- (1095.75 - 21) / 1095.75

# Whole cohort
all <- compute_slope(
  .model_obj = fit, .time_var = "time", .intervention_var = "trt01pn", 
  .spline_var = "spline", .prop = prop, .output = "all"
)


# Fit model (GLP-1RA subgroups) -------------------------------------------

# Recode baseline GLP-1RA use as factor and set `blglp1` == "Yes" as reference
gfr_c <- gfr_c  |> 
  mutate(blglp1 = factor(blglp1, levels = c(1, 0), labels = c("Yes", "No")))

# Fit mixed effects model with unstructured residual variance-covariance matrix
# this time with adjustment and interactions with `blglp1`
fit_subgrp <- lme4::lmer(
  aval ~ base + time * trt01pn + spline * trt01pn + time * blglp1 +
  spline * blglp1 + trt01pn * blglp1 + time * trt01pn * blglp1 + 
  spline * trt01pn * blglp1 - 1 + (time | usubjid), 
  data = gfr_c
)


# Extract model results (GLP-1RA subgroups) -------------------------------

# By GLP1 use
sg <- compute_slope(
  .model_obj = fit_subgrp, .time_var = "time", .intervention_var = "trt01pn", 
  .spline_var = "spline", .prop = prop, .by = "blglp1", .output = "all"
)